author: Daniel Scalzi
description: Create and use realistic elevators in Minecraft.
main: com.dscalzi.realisticelevators.Main
name: RealisticElevators
version: 0.3.0
depend: [WorldEdit]
commands:
  realisticelevators:
    description: Use to access the plugin's subcommands.
    aliases: [re, elevators]
permissions:
  realisticelevators.use:
    default: OP